### PR TITLE
Moving from Fastlane to Triple-T

### PR DESCRIPTION
**Pull request by twilight1794**
App metadata is a mess, there are no distinction between flavors, and there is on F-Droid some outdated content. I've updated all, in English, Spanish and Esperanto, and created new graphics for each flavor. I've stored the sources of these graphics in `/other/1.xcf` and `app/src/<flavor>/res/xml/feature-graphic.svg`.

This resolves first task of #1, and [issue 109 on GitLab](https://gitlab.com/xphnx/ameixa/-/issues/109).

### CODE REVIEW

**Comment by Donnnno** [comment]
Cool~!

**Comment by braniii** [comment]
Thx for this contribution. But I am not sure if I can commit to a mirror repository? @twilight1794 is  #1 the reason for open the MR here?

How about pushing this directly into the "candybar" branch of xphnx/ameixa? I rebased #1 to this branch so it would automatically include these changes.

**Comment by braniii** [comment]
I used the patch of your repo to commit it to the candybar branch, so I will close it here. Do you know if we need to change some configs on the FDroid repo as well?

**Comment by twilight1794** [comment]
> is #1 the reason for open the MR here?

Yes, I opened this MR here because Donnno opened Candybar MR here too.

> Do you know if we need to change some configs on the FDroid repo as well?

I don't know if we should request manually the metadata update, or if that is done automatically when a new version of the app is released. Anyway, I think this should be done after the new version release.

**Pull request closed without merging**
